version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
  build:
    newman-collection-run-env-timeout:
    executor: newman/postman-newman-docker
    newman-collection-run-env-working_directory:

    steps:
      - checkout
      - newman/newman-run:
          collection: ./collection/test_reg.postman_collection.json
          environment: ./env/New-lamp-staging.postman_environment.json

